# Generated by Django 6.0.6 on 2026-06-26 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Annual', 'Annual')], default='Casual', max_length=20),
            preserve_default=False,
        ),
    ]
