# Generated by Django 6.0.6 on 2026-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='June 2026', max_length=20),
            preserve_default=False,
        ),
    ]
