# Generated by Django 6.0.6 on 2026-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payroll_net_salary_payroll_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='June 2026', max_length=20),
        ),
    ]
